deity-io/falcon-platform-docs

docs/platform/integration/bigcommerce/features.md
docs/platform/integration/bigcommerce/manual.md

I've added 'embedded checkout' to the features list.

add embedded checkout to the docs

---

docs/platform/integration/bigcommerce/technical.md

Small note about legacy product options

add note about legacy options

---

docs/platform/release/2-3-0.md
sidebars.js

I've added some release notes to the docs. 
Our repos are private so unfortunately we can't link to issues or commits.
The content is mostly taken from https://github.com/deity-io/falcon-platform/blob/dev/CHANGELOG.md
Please feel free to add more content if there are things I've missed.

add release notes

---

docs/platform/integration/bigcommerce/technical.md

This should be enough info for customers who would like to use Falcon for BigCommerce with legacy options.

Add explanation about supported legacy options

---

docs/platform/client/theming/css-mapping.md
docs/platform/cookbook/client/post-css-support.mdx
docusaurus.config.js

- Corrected yarn install command for postcss-loader
- Renamed config to cfg (to prevent duplicate variable name linting issues in the default build config file)
- Removed unnecessary `./`
- Also removed weird indents from css mapping codeblocks

Correct small mistakes

---

docs/platform/integration/bigcommerce/getting-started.md

This link will 404 until we go live later. I'll wait until then to merge this PR

update link to app

---

docs/platform/integration/bigcommerce/technical.md

Add note about the cache and modifier options

add info about product modifiers

---

docs/platform/client/testing.mdx

Add docs for https://github.com/deity-io/falcon-platform/pull/117

add HelmetProvder to FalconClientMock (CU-6aqrc5)

---

docs/platform/client/theming/overview.md

https://app.clickup.com/t/58pkba
Documents a feature introduced in [Falcon #113](https://github.com/deity-io/falcon-platform/pull/113).

Show how to use globalCss as a function (CU-58pkba)

---

docs/platform/cookbook/client/icon.mdx
docs/platform/cookbook/client/post-css-support.mdx
docs/platform/cookbook/client/testing.md
docs/platform/cookbook/client/themeable-component.mdx

I altered a couple of things I noticed in the cookbook section.
This includes a couple of typos, a change to headers to make it consistent with another page and some extra information I thought would be useful.

Fixed some minor cookbook issues

---

package.json
yarn.lock

upgrade docusaurous from 60 -> 66

---

docusaurus.config.js

remove github link from footer

remove github link from footer

---

docs/platform/cloud/dcloud.md

add info about applying env config

add info about applying env config

---

docs/platform/client/schema-json.md
docs/platform/release/2-6-0.md
docs/platform/release/2-6-2.md
docs/platform/release/full-changelog.md
sidebars.js

n.b. - I've got no idea what was in 2.6.0 so i've left it pretty blank

add 2.6.2 notes + schema docs

---

docs/platform/server/events.md
sidebars.js

This is just basic docs. We should expand it later

start event docs

---

docs/platform/integration/wordpress.md

I think this is a bit misleading. Our plugin maybe support these features but Falcon doesn't at the moment

Remove misleading text

---

package.json
yarn.lock

Solves https://github.com/deity-io/falcon-platform-docs/security/dependabot/yarn.lock/node-fetch/open

Updatig docusaurus

---

docs/platform/cloud/dcloud.md
docs/platform/configuration/overview.md
docs/platform/getting-started/configure.md

add info about encrypted env vars. please merge if you're happy with this

update dcloud docs

---

docs/platform/release/2-7-14.md
docs/platform/release/full-changelog.md

add notes about apollo upgrade

update release notes

---

versioned_docs/version-2/platform/client/menu-navbar.md
versioned_sidebars/version-2-sidebars.json

Added documentation for MenuNavbar integration

Added docs for menu navbar

---

versioned_docs/version-2/platform/app-store/overview.md

Adding a short text to outline feature availability

add features text

---

docs/platform/getting-started/prerequisites.md
docs/platform/integration/magento2/getting-started.md

Related changes:
https://github.com/deity-io/falcon-platform/pull/574

updated node and magento package versions

---

docs/platform/integration/commercetools/payments.md
sidebars.js

Add installation steps for payment data in Commerce Tools

add commerce tools payment info
